package BankingApp;


/**
* BankingApp/Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banking.idl
* Friday, June 5, 2026 9:06:08 AM IST
*/

public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Account
