package BankingApp;


/**
* BankingApp/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banking.idl
* Friday, June 5, 2026 9:06:08 AM IST
*/

public interface AccountOperations 
{
  double getBalance (String accNo);
  void deposit (String accNo, double amount);
  void withdraw (String accNo, double amount) throws BankingApp.InsufficientBalance;
} // interface AccountOperations
