package BankingApp;


/**
* BankingApp/InsufficientBalance.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banking.idl
* Friday, June 5, 2026 9:06:08 AM IST
*/

public final class InsufficientBalance extends org.omg.CORBA.UserException
{
  public String message = null;

  public InsufficientBalance ()
  {
    super(InsufficientBalanceHelper.id());
  } // ctor

  public InsufficientBalance (String _message)
  {
    super(InsufficientBalanceHelper.id());
    message = _message;
  } // ctor


  public InsufficientBalance (String $reason, String _message)
  {
    super(InsufficientBalanceHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class InsufficientBalance
